[admiral]
items = ["left", "workspaces",
         "center", "title",
         "right", "volume", "temp", "battery", "clock"]

[workspaces]
path = "./workspaces"

[title]
path = "xtitle -s -t 80"

[volume]
path = "./vol"
reload = 5

[temp]
path = "./temp"
reload = 5

[battery]
path = "./battery"
reload = 10

[clock]
path = "./clock"
reload = 5

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true
