#!/bin/bash

. $HOME/.config/admiral.d/config
cpuIcon=""

usage=$(mpstat 2 1 | awk '$3 ~ /CPU/ { for(i=1;i<=NF;i++) { if ($i ~ /%idle/) field=i } } $3 ~ /all/ { printf("%d",100 - $field) }')
color="$FG"

if [[ $usage -ge 65 ]]; then
    color="$BRED"
elif [[ $usage -ge 50 ]]; then
    color="$YELLOW"
fi
echo " %{F$color}${cpuIcon} %{F$color}${usage}% "
