#!/bin/bash

. $HOME/.config/admiral.d/config
networkIcon=""

if ping -c 1 google.com >> /dev/null 2>&1; then
    echo "%{F$FG}${networkIcon} %{F$FG}Online "
else
    echo "%{F$RED}${networkIcon} %{F$FG}Offline "
fi
