#!/bin/bash

. $HOME/.config/admiral.d/config
tempIcon=""
temp=$(acpi -t | awk '{ printf("%d", $4) }')
color="$FG"

if [[ $temp -ge 55 ]]; then
    color="$BRED"
elif [[ $temp -ge 50 ]]; then
    color="$YELLOW"
fi
echo " %{F$color}${tempIcon} %{F$color}${temp}C "
