#!/bin/bash

. $HOME/.config/admiral.d/config

volumeState=$(ponymix get-volume)

# Determine volume icon depending on the level of volume.
if [[ ${volumeState} -eq 0 ]]; then
    volumeIcon=""
elif [[ ${volumeState} -le 50 ]]; then
    volumeIcon=""
else
    volumeIcon=""
fi

if $(ponymix is-muted); then
    volumeIcon=""
    volumeColor=${RED}
else
    volumeColor=${FG}
fi
echo "%{F$volumeColor}${volumeIcon} %{F$FG}${volumeState}% "
