#!/usr/bin/env python3

import i3ipc

# Create the Connection object that can be used to send commands and subscribe
# to events.
i3 = i3ipc.Connection()

# Define colors
coloractive = '%{U#d9671f}'
colorinactive = '%{F#839496}'
colorwarning = '%{U#6c71c4}'

# Define a callback to be called when you switch workspaces.
def on_workspace_focus(*args):
    workspace_string = ['']

    for w in i3.get_workspaces():
        if w['focused']:
            workspace_string.append(
                coloractive + '%{+u}' + w['name'] + '%{-u}%{U-}'
            )
        elif w['urgent']:
            workspace_string.append(
                colorwarning + '%{+u}' + w['name'] + '%{-u}%{U-}'
            )
        else:
            workspace_string.append(colorinactive + w['name'])

    workspace_string.append('')
    print(' '.join(workspace_string), flush=True)

# Call right away to avoid blank space
on_workspace_focus()

# Subscribe to events
i3.on('workspace', on_workspace_focus)

# Start the main loop and wait for events to come in.
i3.main()
