#!/bin/sh

num_mon=$(bspc query -M | wc -l)
color_normal="%{F#839496}"
color_focused="%{U#D9671F}"
color_urgent="%{U#6C71C4}"

# bspwm internal state
bspc subscribe report |
while read -r line ; do
    wm_infos="${color_normal}"
    IFS=':'
    set -- ${line#?}
    while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
            M*)
                # active monitor
                if [ $num_mon -gt 1 ] ; then
                    wm_infos="$wm_infos  ${color_normal}${name}%{F-} "
                fi
                ;;
            m*)
                # inactive monitor
                if [ $num_mon -gt 1 ] ; then
                    wm_infos="$wm_infos  ${color_normal}${name}%{F-}  "
                fi
                ;;
            O*)
                # focused occupied desktop
                wm_infos="${wm_infos} ${color_normal}${color_focused}%{+u}${name}%{-u}%{U-}%{F-}"
                ;;
            F*)
                # focused free desktop
                wm_infos="${wm_infos} ${color_normal}${color_focused}%{+u}${name}%{-u}%{U-}%{F-}"
                ;;
            U*)
                # focused urgent desktop
                wm_infos="${wm_infos} ${color_normal}${color_urgent}%{+u}${name}%{-u}%{U-}%{F-}"
                ;;
            o*)
                # occupied desktop
                wm_infos="${wm_infos} ${color_normal}${name}%{F-}"
                ;;
            f*)
                # free desktop
                ;;
            u*)
                # urgent desktop
                wm_infos="${wm_infos} ${color_normal}${color_urgent}%{+u}${name}%{-u}%{U-}%{F-}"
                ;;
        esac
        shift
    done
    echo "${wm_infos}"
done
