colors:
  bright:
    black: '#4A4A4A'
    blue: '#787878'
    cyan: '#FF5370'
    green: '#303030'
    magenta: '#EEFFFF'
    red: '#F78C6C'
    white: '#FFFFFF'
    yellow: '#EBCC05'
  cursor:
    cursor: '#DDEEEE'
    text: '#212630'
  normal:
    black: '#ba97ae'
    blue: '#7898FB'
    cyan: '#79ffe1'
    green: '#13CA91'
    magenta: '#FF3299'
    red: '#F07178'
    white: '#EEFFFF'
    yellow: '#FDF200'
  primary:
    background: '#212630'
    foreground: '#EEEEFF'
font:
  bold:
    family: Meslo LG M for Powerline
    style: Bold
  italic:
    family: Meslo LG M for Powerline
    style: Italic
  normal:
    family: Meslo LG M for Powerline
    style: Regular
  offset:
    x: 2
  size: 6
key_bindings:
- chars: "\eOH"
  key: Home
  mode: AppCursor
- chars: "\e[H"
  key: Home
  mode: ~AppCursor
- chars: "\eOF"
  key: End
  mode: AppCursor
- chars: "\e[F"
  key: End
  mode: ~AppCursor
scrolling:
  history: 5000
  multiplier: 3
window:
  decoration: none
  dimensions:
    columns: 37
    lines: 90
  gtk_theme_variant: dark
