#!/bin/sh

"$HOME"/.config/polybar/launch.sh &
sxhkd &

bspc config border_width          3
bspc config window_gap            2
bspc config top_padding           30
bspc config single_monocle        true
bspc config click_to_focus        true
bspc config focused_border_color  \#2de0a7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc monitor "HDMI-A-0" -d 1 2 3 4 5
bspc monitor "DisplayPort-0" -d 6 7 8 9 0

bspc rule -a Gimp state=floating follow=on
bspc rule -a Firefox desktop=^2
bspc rule -a Chromium desktop=^9
bspc rule -a Pinentry follow=on state=floating
bspc rule -a Libreoffice state=tiled
bspc rule -a Blender state=tiled
