#!/bin/sh

"$HOME"/.config/bspwm/barstart &
sxhkd &

bspc config border_width          5
bspc config window_gap            10
bspc config top_padding           40
bspc config focused_border_color  \#B5BD56

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d "I:dev" "II:web" III IV V VI VII VIII IX X

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop=^2
