#!/bin/sh

"$HOME"/.config/polybar/launch.sh &
sxhkd &

bspc config border_width          5
bspc config window_gap            3
bspc config top_padding           20
bspc config single_monocle        true
bspc config focused_border_color  \#2de0a7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d cli browse 3 4 5 6 7 8 9 10

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a Pinentry follow=on state=floating
