#!/bin/bash

export XDG_CONFIG_HOME="$HOME/.config"
eval "$(ssh-agent)"

# Restore Wallpaper
feh --bg-scale ~/Documents/Backgrounds/forest.png &

# Load some X (and related apps) settings.
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Enable numlock
numlockx on

# Set the keyboard layout
setxkbmap it

# Load cursor
xsetroot -cursor_name left_ptr &

# Run PCManFM daemon
pcmanfm -d &

sxhkd -c ~/.config/sxhkd/sxhdkrc &

alacritty &

exec bspwm
