#!/usr/bin/env bash

count=0

disconnected=""
wireless_connected=""
ethernet_connected=""

ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if wget -q --spider http://google.com ; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 25
        else
            network_name=$(iwgetid -r)
            echo "$wireless_connected $network_name" ; sleep 25
        fi
    else
        echo "$disconnected" ; sleep 2
    fi
done
