#!/usr/bin/env bash

count=0

disconnected="睊"
disconnected2="睊"
wireless_connected="直"
ethernet_connected="囹"

ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if wget -q --spider http://google.com ; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 25
        else
            network_name=$(iwgetid -r)
            echo "$wireless_connected $network_name" ; sleep 25
        fi
    else
        echo "$disconnected" ; sleep 0.5
        echo "$disconnected2" ; sleep 0.5
    fi
done
