#!/bin/bash

# Restore Wallpaper
feh --bg-scale ~/Documents/Backgrounds/winter.jpg &

# Load pcf fonts
xset +fp ~/.fonts
xset fp rehash

# Load some X (and related apps) settings.
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Enable numlock
numlockx on

# Set the keyboard layout
setxkbmap it

# Load cursor
xsetroot -cursor_name left_ptr &

# Execute i3, remember the pid
dbus-launch i3 --shmlog-size 26214400 & wmpid=$!

# Run rxvt unicode daemon
urxvtd -q -o -f &

# Run PCManFM daemon
pcmanfm -d

# Now wait for i3
wait $wmpid
