#!/bin/bash

gxmessage "Are you sure you want to shut down your computer?" \
          -center \
          -title "Take action" \
          -font "Sans 10" \
          -default "_Shut down" \
          -buttons "_Cancel":1,"_Log out":2,"_Reboot":3,"_Shut down":4 \
          >/dev/null

case $? in
  1)
    echo "Exit" ;;
  2)
    numlockx off
    sudo session-logout ;;
  3)
    numlockx off
    systemctl reboot ;;
  4)
    numlockx off
    systemctl poweroff ;;
esac
