#!/bin/bash

# Restore Wallpaper
feh --bg-fill ~/Documents/Backgrounds/osu11.jpg &

# Load some X (and related apps) settings.
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Enable numlock
numlockx on

# Set the keyboard layout
setxkbmap it

# Load cursor
xsetroot -cursor_name left_ptr &

# Lock and turn off monitor after 7 minutes of inactivity
xss-lock -- "i3lock -d -c 000000" &

# Execute xmonad, remember the pid
dbus-launch xmonad & wmpid=$!

# Run rxvt unicode daemon
urxvtd -q -o -f &

# Run PCManFM daemon
pcmanfm -d

# Now wait for xmonad
wait $wmpid
